name: Cypress Tests

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.1
      - run: npm ci
  start:
    runs-on: ubuntu-22.04
    needs: [build-and-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: cypress/e2e
          build: npm run build
          start: npm start
